import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';
import Profile from '../react_challenges/describing_ui/Profile';
import Gallery from '../react_challenges/adding_interactivity/state_comp_memory/Gallery';
import LightSwitch from '../react-challenges-paula/adding-interactivity/LightSwitch';
import ColorSwitch from '../react-challenges-paula/adding-interactivity/ColorSwitch';
import Counter from '../react-challenges-paula/adding-interactivity/Counter';

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Chefo's and Peter's React challenges page!
        </h1>

      {/* <Profile /> */}
      {/* <Gallery /> */}
      {/* <LightSwitch /> */}
      <Counter / >
   

      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
