import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import Profile from "../react_challenges/describing_ui/Profile";
import List from "../react_challenges_Paula/describing-the-UI/rendering-lists/List";
import RecipeList from "../react_challenges_Paula/describing-the-UI/rendering-lists/RecipeList";
import Poem from "../react_challenges_Paula/describing-the-UI/rendering-lists/Poem";
import Clock from "../react_challenges_Paula/describing-the-UI/keeping-comp-pure/Clock";
import ProfileList from "../react_challenges_Paula/describing-the-UI/keeping-comp-pure/ProfileList";
import CollapseDiv from "../react_challenges_Paula/describing-the-UI/keeping-comp-pure/CollapseDiv";
import StoryTray from "../react_challenges_Paula/describing-the-UI/keeping-comp-pure/StoryTray";
import Pgallery from "../react_challenges_Paula/describing-the-UI/state-a-comp-memory/Pgallery";
import Scoreboard from "../react_challenges_Paula/describing-the-UI/updating-obj-and-arrays/ScoreBoard";
import Canvas from "../react_challenges_Paula/describing-the-UI/updating-obj-and-arrays/Canvas";
import ShoppingCart from "../react_challenges_Paula/describing-the-UI/updating-obj-and-arrays/UpdateArray";


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to Chefo's and Peter's React challenges page!
        </h1>

        {/* <Profile /> */}
        {/*<Gallery />*/}
        {/*<List/>*/}
        {/* <Poem />
        <RecipeList /> 
        <Clock /> 
        <ProfileList />*/}
        {/* <Clock /> */}
        {/* <StoryTray
          stories={[
            { id: "Mike", label: "story" },
            { id: "Daniel", label: "story" },
            { id: "Daiana", label: "story" },
          ]}
        /> */}
        {/* <Pgallery /> */}
        {/* <Scoreboard /> */}
        {/* <Canvas /> */}
        <ShoppingCart/>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  );
}
